name = "open-house"
main = "src/index.ts"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "open-house-db"
database_id = "11c2a9d3-64c5-4f87-902c-1a7b422b9cd0"

[[kv_namespaces]]
binding = "KV"
id = "1f8e09cbac794744a208e6b15a0dcaaa"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "open-house-photos"

[[routes]]
pattern = "openhouse.primeamericarealestate.com"
custom_domain = true

[vars]
ADMIN_SECRET = "change-this-secret-in-production"
JWT_SECRET = "super-secret-jwt-key-replace-in-prod"
APP_URL = "https://openhouse.primeamericarealestate.com"
